// module.exports = {
//   someSidebar: {
//     'Getting Started': ['styleGuide', 'aboutMe', 'doc3'],
//     Features: ['mdx'],
//   }
// };

// const { listPaths } = require('./src/components');

// let workingDocs = listPaths('working');

module.exports = {
  someSidebar: [{type: 'autogenerated', dirName: '.'}],
};

